name: hadith_nawawi
description: "Hadith Nawawi Package Hadith Nawawi Package is a Flutter package designed to provide access to the esteemed collection of Arba'in Al-Nawawi (الأربعين النووية), a compilation of forty hadiths by Imam Nawawi. This package allows for easy integration into your Flutter applications, offering a seamless way to access and display these foundational hadiths."
version: 0.0.1
repository: https://github.com/Kandil7/hadith_nawawi

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/hadiths.json
