name: hadith_nawawi
description: "A Flutter package providing access to the collection of Arba'in Al-Nawawi (الأربعين النووية), a compilation of forty hadiths by Imam Nawawi. Includes UI components, search functionality, and multilingual support."
version: 0.0.2
homepage: https://github.com/Kandil7/hadith_nawawi
repository: https://github.com/Kandil7/hadith_nawawi.git
issue_tracker: https://github.com/Kandil7/hadith_nawawi/issues

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/hadiths.json
